/** Ordered map of parser key → display label. Mirrors VENDOR_LABELS in app.py. */
export const VENDORS: Record<string, string> = {
  advantage:        'Advantage Truck Group',
  americantextile:  'American Textile Mills',
  arcsource:        'ArcSource Inc.',
  berubes:          "Berube's Truck Accessories",
  brookline:        'Brookline Machine / APW',
  burkeoil:         'Dennis K Burke Inc',
  castle:           'Castle Packs / Finger Lakes',
  cdk:              "CDK Global (Ballard, Lucky's, Grappone, Portsmouth Ford)",
  cohensteel:       'Cohen Steel Supply Inc.',
  cummins:          'Cummins Inc',
  dennison:         'Dennison Lubricants',
  fastenerwarehouse:'Fastener Warehouse',
  fleetpride:       'FleetPride',
  hewsco:           'Hews Company LLC',
  keystone:         'Keystone Automotive (LKQ)',
  kimball:          'Kimball Midwest',
  kljack:           'K.L. Jack & Co.',
  mcfarlandford:    'McFarland Ford Sales Inc.',
  myers:            'Myers Tire Supply',
  nationaltire:     'National Tire Wholesale',
  nekw:             'New England Kenworth',
  omni:             'Omni Services',
  rctoolbox:        'RC Toolbox',
  rochestertruck:   'Rochester Truck',
  stmt_unknown:     'Unknown Vendor (acct 63168)',
  sullivan:         'Sullivan Tire',
  terminalsupply:   'Terminal Supply Co.',
  unitedpacific:    'United Pacific Industries',
  whelen:           'Whelen Engineering',
  wisupply:         'WI Supply Boston',
  zips:             'Zips Truck Equipment (OCR / Scanned)',
};

export const VENDOR_KEYS = Object.keys(VENDORS);
